# Generated by Django 4.2.6 on 2023-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('job_description', models.TextField()),
            ],
        ),
    ]
